PS_proj/PS_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('', include('dogs.urls', namespace='dogs')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

PS_proj/dogs/urls.py
from django.urls import path
from . import views

app_name = 'dogs'


urlpatterns = [
    path('dogs', views.dogs, name='dogs'),
    path('curators', views.curators, name='curators'),
    path('owners', views.owners, name='owners'),
    path('potential_owners', views.potential_owners, name='potential_owners'),
    path('add_dog', views.add_dog, name='add_dog'),
    path('add_curator', views.add_curator, name='add_curator'),
    path('add_owner', views.add_owner, name='add_owner'),
    path('add_adoption/<int:owner_id>/', views.add_adoption,
         name='add_adoption'
         ),
    path('adoption_exist_owner', views.adoption_exist_owner,
         name='adoption_exist_owner'
         ),
    path('edit_dog/<int:dog_id>/', views.edit_dog, name='edit_dog'),
    path('edit_curator/<int:curator_id>/', views.edit_curator,
         name='edit_curator'
         ),
    path('edit_owner/<int:owner_id>/', views.edit_owner, name='edit_owner'),
    path('audition/<int:adoption_id>/', views.audition,
         name='audition'
         ),
    path('owners_to_audit', views.owners_to_audit,
         name='owners_to_audit'
         ),
    path('profile_dog/<int:dog_id>', views.profile_dog, name='profile_dog'),
    path('profile_curator/<int:curator_id>', views.profile_curator,
         name='profile_curator'
         ),
    path('profile_owner/<int:owner_id>', views.profile_owner,
         name='profile_owner'
         ),
    path('adoption_info/<int:adoption_id>', views.adoption_info,
         name='adoption_info'
         ),
    path('contract/<int:adoption_id>/', views.contract,
         name='contract'
         ),
    path('adoptions_to_contract', views.adoptions_to_contract,
         name='adoptions_to_contract'
         )
]

PS_proj/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

PS_proj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>    
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <title>
        {% block title %}
            title
        {% endblock %}
        </title>
    </head>
    <body>
        <header>
            {% include 'header.html' %}
        </header>
        <main>
        {% block content %}
            content
        {% endblock %}
        </main>   
        <footer class="border-top text-center py-3">
            {% comment %} {% include 'includes/footer.html' %} {% endcomment %}
        </footer>
    </body>

PS_proj/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand">PS_proj</a>
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index:index' %}">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{request.META.HTTP_REFERER}}">Назад</a>
          </li>
        </ul>
    </div>
  </nav>

PS_proj/templates/index.html
{% extends 'base.html' %}
{% block title %}
  	Главная
{% endblock %}
{% block content %}
	<h3 class="container py-3">Главная</h3>
    <div class="container py-1">
        <div class="row">
            <aside class="col-12 col-md-6">
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-primary" href="{% url 'dogs:dogs' %}">Каталог собак</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-primary" href="{% url 'dogs:curators' %}">Каталог кураторов</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-primary" href="{% url 'dogs:owners' %}">Каталог хозяев (подписан договор)</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-primary" href="{% url 'dogs:potential_owners' %}">Каталог потенциальных хозяев</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-secondary" href="{% url 'dogs:add_dog' %}">Добавить собаку в каталог</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-secondary" href="{% url 'dogs:add_curator' %}">Добавить куратора в каталог</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-secondary" href="{% url 'dogs:adoption_exist_owner' %}">Пристроить собаку существующему хозяину</a>
                </div><br>
            </aside>
            <aside class="col-12 col-md-6">
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-info" href="{% url 'dogs:add_owner' %}">Зарегистрировать потенциального хозяина</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-info" href="{% url 'dogs:owners_to_audit' %}">Провести собеседование</a>
                </div><br>
                <div class="d-grid gap-2">
                    <a class="btn btn-lg btn-info" href="{% url 'dogs:adoptions_to_contract' %}">Заполнить и подписать договор</a>
                </div><br>
            </aside>
        </div>
	</div>
{% endblock %}