PS_proj/PS_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('', include('dogs.urls', namespace='dogs')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

PS_proj/dogs/urls.py
from django.urls import path
from . import views

app_name = 'dogs'


urlpatterns = [
    path('dogs', views.dogs, name='dogs'),
    path('curators', views.curators, name='curators'),
    path('owners', views.owners, name='owners'),
    path('potential_owners', views.potential_owners, name='potential_owners'),
    path('add_dog', views.add_dog, name='add_dog'),
    path('add_curator', views.add_curator, name='add_curator'),
    path('add_owner', views.add_owner, name='add_owner'),
    path('add_adoption/<int:owner_id>/', views.add_adoption,
         name='add_adoption'
         ),
    path('adoption_exist_owner', views.adoption_exist_owner,
         name='adoption_exist_owner'
         ),
    path('edit_dog/<int:dog_id>/', views.edit_dog, name='edit_dog'),
    path('edit_curator/<int:curator_id>/', views.edit_curator,
         name='edit_curator'
         ),
    path('edit_owner/<int:owner_id>/', views.edit_owner, name='edit_owner'),
    path('audition/<int:adoption_id>/', views.audition,
         name='audition'
         ),
    path('owners_to_audit', views.owners_to_audit,
         name='owners_to_audit'
         ),
    path('profile_dog/<int:dog_id>', views.profile_dog, name='profile_dog'),
    path('profile_curator/<int:curator_id>', views.profile_curator,
         name='profile_curator'
         ),
    path('profile_owner/<int:owner_id>', views.profile_owner,
         name='profile_owner'
         ),
    path('adoption_info/<int:adoption_id>', views.adoption_info,
         name='adoption_info'
         ),
    path('contract/<int:adoption_id>/', views.contract,
         name='contract'
         ),
    path('adoptions_to_contract', views.adoptions_to_contract,
         name='adoptions_to_contract'
         )
]

PS_proj/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

PS_proj/dogs/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

CHOICES = [
            ('OK', 'Пройдено'),
            ('DENY', 'Отказ'),
            ('Not_auditioned', 'Не собеседовался')
        ]


class Curator(models.Model):
    name = models.CharField('ФИО куратора', max_length=200)
    tel = models.CharField(
        'Телефон без префикса (10 цифр)',
        max_length=10
    )
    pound = models.CharField(
        'Приют',
        max_length=200,
        blank=True,
        null=True
    )
    add_date = models.DateTimeField(
        'Дата добавления',
        auto_now_add=True
    )
    passport_no = models.CharField(
        'Серия и номер паспорта',
        max_length=10,
        blank=True,
        null=True
    )
    passport_issued = models.CharField(
        'Кем выдан',
        max_length=200,
        blank=True,
        null=True
    )
    passport_code = models.CharField(
        'Код подразделения',
        max_length=7,
        blank=True,
        null=True
    )
    passport_date = models.DateField(
        'Дата выдачи',
        blank=True,
        null=True
    )
    address_reg = models.CharField(
        'Адрес регистрации',
        max_length=500,
        blank=True,
        null=True
    )
    email = models.EmailField(
        'Email',
        blank=True,
        null=True
    )

    class Meta:
        ordering = ['name']
        verbose_name = "Куратор"
        verbose_name_plural = "Кураторы"

    def __str__(self):
        return self.name


class Dog(models.Model):
    name = models.CharField('Кличка', max_length=200)
    curator = models.ForeignKey(
        Curator,
        on_delete=models.SET_NULL,
        null=True,
        max_length=200,
        related_name='curator',
        verbose_name="Куратор"
    )
    add_date = models.DateTimeField(
        'Дата добавления',
        auto_now_add=True
    )
    # image = models.ImageField(
    #     'Фото',
    #     upload_to='dogs/',
    #     blank=True
    # )

    class Meta:
        ordering = ['name']
        verbose_name = "Собака"
        verbose_name_plural = "Собаки"

    def __str__(self):
        return self.name


class Owner(models.Model):
    name = models.CharField('ФИО хозяина', max_length=200)
    tel = models.CharField(
        'Телефон без префикса (10 цифр)',
        max_length=10
    )

    add_date = models.DateTimeField(
        'Дата добавления',
        auto_now_add=True
    )
    passport_no = models.CharField(
        'Серия и номер паспорта',
        max_length=10,
        blank=True,
        null=True
    )
    passport_issued = models.CharField(
        'Кем выдан',
        max_length=200,
        blank=True,
        null=True
    )
    passport_code = models.CharField(
        'Код подразделения',
        max_length=7,
        blank=True,
        null=True
    )
    passport_date = models.DateField(
        'Дата выдачи',
        blank=True,
        null=True
    )
    address_reg = models.CharField(
        'Адрес регистрации',
        max_length=500,
        blank=True,
        null=True
    )
    address_fact = models.CharField(
        'Адрес проживания',
        max_length=500,
        blank=True,
        null=True
    )
    email = models.EmailField(
        'Email',
        blank=True,
        null=True
    )
    discount_card = models.CharField(
        'Номер карты Коммондор',
        max_length=10,
        blank=True,
        null=True
    )

    class Meta:
        ordering = ['-add_date']
        verbose_name = "Хозяин"
        verbose_name_plural = "Хозяева"

    def __str__(self):
        return self.name


class Adoption(models.Model):
    owner = models.ForeignKey(
        Owner,
        on_delete=models.CASCADE,
        related_name='dog_owner',
        verbose_name='Хозяин'
    )
    dog = models.ForeignKey(
        Dog,
        on_delete=models.CASCADE,
        related_name='adopted_dog',
        verbose_name='Собака'
    )
    add_date = models.DateTimeField(
        'Дата добавления',
        auto_now_add=True
    )
    contract_signed = models.BooleanField(
        'Договор подписан',
        default=False,
        blank=True,
        null=True
    )
    sobes_status = models.CharField(
        'Статус собеседования',
        max_length=200,
        choices=CHOICES,
        default='Not_auditioned',
        blank=False,
        null=True
    )
    sobes_result = models.TextField(
        'Комментарий',
        max_length=1000,
        blank=True,
        null=True
    )
    had_pets = models.BooleanField(
        'Были ли домашние животные',
        blank=True,
        null=True
    )
    large_place = models.BooleanField(
        'Огромная квартира',
        blank=True,
        null=True
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['owner', 'dog'],
                name='unique_adoption'
            ),
            models.UniqueConstraint(
                fields=['dog', 'contract_signed'],
                name='unique_contract'
            )
        ]
        ordering = ['-add_date']
        verbose_name = "Пристройство"
        verbose_name_plural = "Пристройства"

    def __str__(self):
        adoption = f'{self.owner} и {self.dog}'
        return adoption

PS_proj/dogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from core.paginator import paginator
from .models import Dog, Curator, Owner, Adoption
from .forms import (DogForm, CuratorForm, AddOwnerForm, ContractOwnerForm,
                    AuditForm, AdoptionForm, EditOwnerForm,
                    ContractAdoptionForm, AdoptionExistOwnerForm)


def dogs(request):
    '''Список всех собак'''
    dogs = Dog.objects.select_related('curator')
    context = {
        'page_object': paginator(request, dogs)
    }
    return render(request, 'dogs/dogs.html', context)


def curators(request):
    '''Список всех кураторов'''
    curators = Curator.objects.all()
    context = {
        'dogs': dogs,
        'page_object': paginator(request, curators)
    }
    return render(request, 'dogs/curators.html', context)


def owners(request):
    '''Список всех владельцев собак (есть собака и подписанный договор)'''
    owners = Owner.objects.exclude(
        dog_owner__dog__isnull=True).filter(dog_owner__contract_signed=True)
    context = {
        'page_object': paginator(request, owners)
    }
    return render(request, 'dogs/owners.html', context)


def potential_owners(request):
    '''Список всех потенциальных владельцев (зарегистрирован в базе,
    нет подписанного договора, возможно не указана собака'''
    owners = Owner.objects.exclude(dog_owner__contract_signed=True)
    context = {
        'potential': True,
        'page_object': paginator(request, owners)
    }
    return render(request, 'dogs/owners.html', context)


def add_dog(request):
    '''Добавляет собаку в каталог'''
    form = DogForm(
        request.POST or None
    )
    if not request.method == 'POST' or not form.is_valid():
        return render(request, 'dogs/add_dog.html', {'form': form})
    form.save()
    return redirect('dogs:dogs')


def add_curator(request):
    '''Добавляет куратора в каталог'''
    form = CuratorForm(
        request.POST or None
    )
    if not request.method == 'POST' or not form.is_valid():
        return render(request, 'dogs/add_curator.html', {'form': form})
    form.save()
    return redirect('dogs:curators')


def add_owner(request):
    '''Шаг 1 процесса выставки.
    Добавляет потенциального хоза в каталог,
    редиректит на создание адопшена - add_adoption'''
    form_owner = AddOwnerForm(request.POST or None)
    if not request.method == 'POST' or not form_owner.is_valid():
        return render(
            request,
            'dogs/add_owner.html',
            {'form_owner': form_owner}
        )
    instance = form_owner.save(commit=False)
    form_owner.save()
    return redirect('dogs:add_adoption', instance.id)


def add_adoption(request, owner_id):
    '''Шаг 2 процесса выставки.
    Создается инстанс адопшена, к указанному хозу в предыдущем шаге
    (add_owner) привязывается выбранная собака'''
    owner = get_object_or_404(Owner, pk=owner_id)
    form_owner = AdoptionForm(request.POST or None)
    if not request.method == 'POST' or not form_owner.is_valid():
        context = {
            'form_owner': form_owner,
            'adopt': True
        }
        return render(request, 'dogs/add_owner.html', context)

    instance = form_owner.save(commit=False)
    instance.owner = owner
    form_owner.save()
    return redirect('dogs:add_owner')


def adoption_exist_owner(request):
    '''Привязывает собаку из каталога к хозу из каталога'''
    form_owner = AdoptionExistOwnerForm(request.POST or None)
    if not request.method == 'POST' or not form_owner.is_valid():
        context = {
            'form_owner': form_owner,
            'adopt_exist': True
        }
        return render(request, 'dogs/add_owner.html', context)
    form_owner.save()
    return redirect('/')


def edit_dog(request, dog_id):
    '''Редактирование данных собаки'''
    dog = get_object_or_404(Dog, id=dog_id)
    form = DogForm(
        request.POST or None,
        instance=dog
    )
    if form.is_valid():
        form.save()
        return redirect('dogs:dogs')
    context = {
        'is_edit': True,
        'form': form
    }
    return render(request, 'dogs/add_dog.html', context)


def edit_curator(request, curator_id):
    '''Редактирование данных куратора'''
    curator = get_object_or_404(Curator, id=curator_id)
    form = CuratorForm(
        request.POST or None,
        instance=curator
    )
    if form.is_valid():
        form.save()
        return redirect('dogs:curators')
    context = {
        'is_edit': True,
        'form': form
    }
    return render(request, 'dogs/add_curator.html', context)


def edit_owner(request, owner_id):
    '''Редактирование данных хозяина, редиректит на список
    хозов или потенциальных хозов'''
    owner = get_object_or_404(Owner, id=owner_id)
    dogs = Dog.objects.filter(adopted_dog__owner=owner)
    adoptions = owner.dog_owner.all()
    real_owner = any([i.contract_signed for i in adoptions])
    form_owner = EditOwnerForm(
        request.POST or None,
        instance=owner
    )
    if form_owner.is_valid():
        form_owner.save()
        if real_owner:
            return redirect('dogs:owners')
        return redirect('dogs:potential_owners')
    context = {
        'dogs': dogs,
        'is_edit': True,
        'form_owner': form_owner
    }
    return render(request, 'dogs/add_owner.html', context)


def audition(request, adoption_id):
    '''Шаг 4 процесса выставки.
    Заполняются данные собеседования и вносятся в выбранный адопшен'''
    adoption = get_object_or_404(Adoption, id=adoption_id)
    dog = adoption.dog
    owner = adoption.owner
    form_adoption = AuditForm(
        request.POST or None,
        instance=adoption
    )
    if form_adoption.is_valid():
        form_adoption.save()
        return redirect('dogs:owners_to_audit')
    context = {
        'owner': owner,
        'dog': dog,
        'audit': True,
        'form_adoption': form_adoption
    }
    return render(request, 'dogs/add_owner.html', context)


def owners_to_audit(request):
    '''Шаг 3 процесса выставки.
    Список адопшенов, у которых нет подписанного контракта,
    статус собеседования - не пройден'''
    adoptions = Adoption.objects.filter(
        sobes_status='Not_auditioned',
        contract_signed='False'
    )
    context = {
        'page_object': paginator(request, adoptions)
    }
    return render(request, 'dogs/owners_to_proceed.html', context)


def profile_dog(request, dog_id):
    '''Информация о выбранной собаке'''
    dog = get_object_or_404(Dog, id=dog_id)
    try:
        owner = Owner.objects.filter(
            dog_owner__dog=dog,
            dog_owner__contract_signed=True
        ).get()
    except Owner.DoesNotExist:
        owner = False
    context = {
        'dog': dog,
        'owner': owner
    }
    return render(request, 'dogs/profile_dog.html', context)


def profile_curator(request, curator_id):
    '''Информация о выбранном кураторе'''
    curator = get_object_or_404(Curator, id=curator_id)
    dogs = curator.curator.select_related('curator')
    context = {
        'dogs': dogs,
        'curator': curator
    }
    return render(request, 'dogs/profile_curator.html', context)


def profile_owner(request, owner_id):
    '''Информация о выбранном хозе/потенциальном хозе'''
    owner = get_object_or_404(Owner, id=owner_id)
    dogs = Dog.objects.filter(
        adopted_dog__owner=owner,
        adopted_dog__contract_signed=True
    )
    adoptions = Adoption.objects.filter(owner=owner)
    contract_signed = any([i.contract_signed for i in adoptions])
    context = {
        'dogs': dogs,
        'owner': owner,
        'adoptions': adoptions,
        'contract_signed': contract_signed
    }
    return render(request, 'dogs/profile_owner.html', context)


def contract(request, adoption_id):
    '''Шаг 6 процесса выставки.
    У выбранного адопшена устанавливается True в графе "договор подписан"'''
    adoption = get_object_or_404(Adoption, id=adoption_id)
    owner = adoption.owner
    form_owner = ContractOwnerForm(
        request.POST or None,
        instance=owner
    )
    form_adoption = ContractAdoptionForm(
        request.POST or None,
        instance=adoption
    )
    if (
        not request.method == 'POST'
        or not form_owner.is_valid()
        or not form_adoption.is_valid()
         ):
        context = {
            'form_owner': form_owner,
            'form_adoption': form_adoption,
            'dogs': dogs,
            'contract': True
        }
        return render(request, 'dogs/add_owner.html', context)
    form_owner.save()
    form_adoption.save()
    return redirect('dogs:adoptions_to_contract')


def adoptions_to_contract(request):
    '''Шаг 5 процесса выставки.
    Список адопшенов, у которых нет подписанного контракта
    и нет отказа в статусе собеседования'''
    adoptions = Adoption.objects.filter(contract_signed=False).exclude(
        sobes_status='DENY')
    context = {
        'page_object': paginator(request, adoptions)
    }
    return render(request, 'dogs/adoptions_to_proceed.html', context)


def adoption_info(request, adoption_id):
    '''Информация о пристройстве (пара собака-хозяин)'''
    adoption = get_object_or_404(Adoption, id=adoption_id)
    context = {
        'adoption': adoption
    }
    return render(request, 'dogs/adoption_info.html', context)

PS_proj/templates/dogs/add_curator.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Изменить информацию о кураторе
  {% else %}
    Добавить куратора
  {% endif %}
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Изменить информацию о кураторе
              {% else %}
                Добавить куратора в каталог
              {% endif %}
            </div>
            <div class="card-body">
              <form method="post">
                <action="{% url 'dogs:add_dog' %}">
              {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <span style="color:red">{{ field.errors }}</span>
                    <label>
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger" >*</span>
                      {% endif %}
                    </label>
                    {{ field }}
                  </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

PS_proj/templates/dogs/adoption_info.html
{% extends 'base.html' %}
{% block title %}
    Пристройство
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-4">
        {% comment %} <img src="{% static 'img/elite.jpg' %}" {% endcomment %}
        {% comment %} width="400" height="400"
        class="d-inline-block align-top" alt=""> {% endcomment %}
      </aside>
      <article class="col-12 col-md-8">
        <h3>{{ adoption.owner }} и <a href="{% url 'dogs:profile_dog' adoption.dog.id %}">{{ adoption.dog }}</a></h3>
        <ul>
          {% if adoption.contract_signed %}
            <span style="color:blue">Договор подписан</span>
          {% else %}
            <span style="color:red">Договор не подписан</span>
          {% endif %}
        </ul>
        <ul>
          <li>
            <b>Дата:</b> {{ adoption.add_date|date:'d E Y' }}
          </li>
          <li>
          <b>Собеседование:</b> {{ adoption.get_sobes_status_display }}<br>
            {% if adoption.sobes_result %}
              Комментарий: {{ adoption.sobes_result }}
              {% endif %}
          </li>
          {% if not adoption.sobes_status == 'Not_auditioned' %}
            <li>
            <b>Анкета:</b><br>
              Были ли домашние животные: {% if adoption.had_pets %}Да{% else %}Нет{% endif %}<br>
              Огромная квартира: {% if adoption.large_place %}Да{% else %}Нет{% endif %}
            </li
          {% endif %}
        </ul>
      </article>
    </div>     
  </div>
{% endblock %}

PS_proj/templates/dogs/adoptions_to_proceed.html
{% extends 'base.html' %}
{% block title %}
  	Договор
{% endblock %}
{% block content %}
	<h3 class="container py-3">
  		Оформить договор
	</h3>
	<div class="container py-1">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">Пристройство</th>
					<th scope="col">Собеседование</th>
                    <th scope="col">Добавлено</th>
				</tr>
			</thead>
			{% for object in page_object %}
			<tbody>
				<tr>
					<th scope="row">
                        <a href="{% url 'dogs:contract' object.id %}">{{ object }}</a>
                    </th>
					<td>{{ object.get_sobes_status_display }}</td>
					<td>{{ object.add_date|date:'d E Y' }} {{ object.add_date|time:"H:i" }}</td>
				</tr>
			</tbody>
			{% endfor %}
		</table>
		{% include 'dogs/includes/paginator.html' %}
	</div>
{% endblock %}

PS_proj/templates/dogs/curators.html
{% extends 'base.html' %}
{% block title %}
  	Каталог кураторов
{% endblock %}
{% block content %}
	<h3 class="container py-3">Каталог кураторов</h3>
	<div class="container py-1">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">ФИО</th>
					<th scope="col">Приют</th>
                    <th scope="col">Добавлен</th>
				</tr>
			</thead>
			{% for object in page_object %}
			<tbody>
				<tr>
					<th scope="row">
						<a href="{% url 'dogs:profile_curator' object.id %}">
                            {{ object }}
                        </a>
					</th>
					<td>{{ object.pound }}</td>
					<td>{{ object.add_date|date:'d E Y' }}</td>
				</tr>
			</tbody>
			{% endfor %}
		</table>
		{% include 'dogs/includes/paginator.html' %}
	</div>
{% endblock %}

PS_proj/templates/dogs/owners_to_proceed.html
{% extends 'base.html' %}
{% block title %}
	{% if contract %}
		Подписание договора
	{% else %}
  		Собеседование
	{% endif %}
{% endblock %}
{% block content %}
	<h3 class="container py-3">
		{% if contract %}
			Претенденты на подписание договора
		{% else %}
  			Претенденты на собеседование
		{% endif %}
	</h3>
	<div class="container py-1">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">ФИО</th>
                    <th scope="col">Добавлен</th>
				</tr>
			</thead>
			{% for object in page_object %}
			<tbody>
				<tr>
					<th scope="row">
						{% if contract %}
							<a href="{% url 'dogs:contract' object.id %}">{{ object }}</a>
						{% else %}
                        	<a href="{% url 'dogs:audition' object.id %}">{{ object }}</a>
						{% endif %}
                    </th>
					<td>{{ object.add_date|date:'d E Y' }} {{ object.add_date|time:"H:i" }}</td>
				</tr>
			</tbody>
			{% endfor %}
		</table>
		{% include 'dogs/includes/paginator.html' %}
	</div>
{% endblock %}

PS_proj/templates/dogs/profile_curator.html
{% extends 'base.html' %}
{% block title %}
    Информация о кураторе
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-4">
        {% comment %} <img src="{% static 'img/elite.jpg' %}" {% endcomment %}
        {% comment %} width="400" height="400"
        class="d-inline-block align-top" alt=""> {% endcomment %}
      </aside>
      <article class="col-12 col-md-8">
        <h3>{{ curator.name }} (куратор)</h3>
        <ul>
          <li>
            Телефон: +7-{{ curator.tel|slice:':3' }}-{{ curator.tel|slice:'3:' }}
          </li>
          {% if curator.email %}
            <li>
              Email: {{ curator.email }}
            </li>
          {% endif %}
          {% if curator.passport_no %}
          <li>
            Паспорт: {{ curator.passport_no|slice:':4' }} {{ curator.passport_no|slice:'4:' }}<br>
            Кем выдан: {{ curator.passport_issued|default_if_none:"нет информации" }}<br>
            Когда выдан: {{ curator.passport_date|default_if_none:"нет информации" }}<br>
            Код подразделения: {{ curator.passport_code|default_if_none:"нет информации" }}<br>
          </li>
          <li>
            Адрес регистрации: {{ curator.address_reg|default_if_none:"нет информации" }}
          </li>
        {% else %}
          Паспорт: нет информации
        {% endif %}
        </ul>
        <h3>Собаки</h3>
        <ul>
            {% for dog in dogs %}
                <li>
                  <a href="{% url 'dogs:profile_dog' dog.id %}">{{ dog }}</a>
                </li>
            {% endfor %}
        </ul>
        <a class="btn btn-lg btn-secondary" href="{% url 'dogs:edit_curator' curator.id %}">Редактировать</a>
      </article>
    </div>     
  </div>
{% endblock %}

PS_proj/templates/dogs/profile_dog.html
{% extends 'base.html' %}
{% block title %}
  Информация о собаке
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-4">
        {% comment %} <img src="{% static 'img/elite.jpg' %}" {% endcomment %}
        {% comment %} width="400" height="400"
        class="d-inline-block align-top" alt=""> {% endcomment %}
      </aside>
      <article class="col-12 col-md-8">
        <h2>{{ dog.name }}</h2><br>        
        {% if owner %}
            <h4>Хозяин: 
              <a href="{% url 'dogs:profile_owner' owner.id %}">{{ owner.name }}</a>
            </h4>
            <ul>
            <li>
              Телефон: +7-{{ owner.tel|slice:':3' }}-{{ owner.tel|slice:'3:' }}
            </li>
            </ul>
        {% endif %}
        <h4>Куратор: 
          <a href="{% url 'dogs:profile_curator' dog.curator.id %}">{{ dog.curator.name }}</a>
        </h4>
        <ul>
          <li>
            Телефон: +7-{{ dog.curator.tel|slice:':3' }}-{{ dog.curator.tel|slice:'3:' }}
          </li>
          {% if dog.curator.email %}
          <li>
            Email: {{ dog.curator.email }}
          </li>
          {% endif %}
          <li>
            Приют: {{ dog.curator.pound }}
          </li>
        </ul>
        <a class="btn btn-lg btn-secondary" href="{% url 'dogs:edit_dog' dog.id %}">Редактировать</a>
      </article>
    </div>     
  </div>
{% endblock %}

PS_proj/templates/dogs/profile_owner.html
{% extends 'base.html' %}
{% block title %}
    Информация о хозяине
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-4">
        {% comment %} <img src="{% static 'img/elite.jpg' %}" {% endcomment %}
        {% comment %} width="400" height="400"
        class="d-inline-block align-top" alt=""> {% endcomment %}
      </aside>
      <article class="col-12 col-md-8">
        <h3>
          {{ owner.name }}
          ({% if not contract_signed %}потенциальный {% endif %}хозяин)
        </h3>
        <ul>
          <li>
            Телефон: +7-{{ owner.tel|slice:':3' }}-{{ owner.tel|slice:'3:' }}
          </li>
          {% if owner.email %}
            <li>
              Email: {{ owner.email }}
            </li>
          {% endif %}
          {% if owner.passport_no %}
            <li>
              Паспорт: {{ owner.passport_no|slice:':4' }} {{ owner.passport_no|slice:'4:' }}<br>
              Кем выдан: {{ owner.passport_issued|default_if_none:"нет информации" }}<br>
              Когда выдан: {{ owner.passport_date|default_if_none:"нет информации" }}<br>
              Код подразделения: {{ owner.passport_code|default_if_none:"нет информации" }}<br>
            </li>
            <li>
              Адрес регистрации: {{ owner.address_reg|default_if_none:"нет информации" }}
            </li>
            <li>
              Адрес проживания: {{ owner.address_fact|default_if_none:"нет информации" }}
            </li>
          {% else %}
            Паспорт: нет информации
          {% endif %}
          <li>
            Карта Коммондор: {{ owner.discount_card|default_if_none:"нет" }}
          </li>
        </ul>
        {% if dogs %}
          <h3>Собак{% if dogs.count > 1 %}и{% else %}а{% endif %}</h3>
          <ul>
            {% for dog in dogs %}
                <li>
                    <a href="{% url 'dogs:profile_dog' dog.id %}">{{ dog.name }}</a>
                </li>
            {% endfor %}
          </ul>
        {% endif %}
        {% if adoptions %}
          <h3>Пристройств{% if adoptions.count > 1 %}а{% else %}о{% endif %}</h3>
          <ul>
            {% for adoption in adoptions %}
                <li>
                  <a href="{% url 'dogs:adoption_info' adoption.id %}">{{ adoption }}</a>
                  {% if not adoption.contract_signed %}(не состоялось){% endif %}
                </li>
            {% endfor %}
          </ul>
        {% endif %}
        <a class="btn btn-lg btn-secondary" href="{% url 'dogs:edit_owner' owner.id %}">Редактировать</a>
      </article>
    </div>     
  </div>
{% endblock %}